FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:18-alpine AS dev
WORKDIR /app
EXPOSE 5173
ENV NODE_ENV=development
COPY --from=build /app/package*.json ./
COPY --from=build /app/.svelte-kit ./.svelte-kit
RUN npm install vite
ENV HOST=127.0.0.1
ENV PORT=5173
CMD ["npm", "run", "dev", "--host"]

