FROM node:alpine AS build
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build

FROM node:alpine AS run
WORKDIR /app
COPY --from=build /app/package*.json ./
RUN npm ci --production --ignore-scripts
COPY --from=build /app/build ./
EXPOSE 3000
CMD ["node", "./index.js"]